### ISSUE TITLE
グローバルBan申請の証拠未添付問題

### ISSUE THREAD

**Issue by Aoichaan0513** [LunaProject-Discord/Issues#16]
グローバルBanの申請方法を変更することにより証拠の未添付問題を解決する。

### 現行
コマンドでの申請実行 → 被申請者に対するサーバーログ、メッセージログなどの収集
　　　　　　　　　　 → 収集できた場合、証拠の添付についてを記載せずに申請完了メッセージを送信
　　　　　　　　　　 → 収集できない場合、証拠を添付する旨のメッセージを記載して申請完了メッセージを送信

### 変更案１
コマンドでの申請実行 → 証拠を添付する旨のダイアログを送信 → ユーザーが証拠を添付した後に現行での方法にて申請開始
― **夜龍 瑞葉**#3322
### 変更案２
コマンドでの申請実行 → 証拠を添付する旨のメッセージを送信 → 確認リアクションを追加した後、現行での方法にて申請開始

**Comment by Saroniii** [comment]
変更案2に賛成。

**Comment by Aoichaan0513** [comment]
グローバルBanの廃止のためクローズ
