### ISSUE TITLE
ホームページの認証済みサーバーページでhomeアイコンがしっかり表示されない

### ISSUE THREAD

**Issue by narikakun** [LunaProject-Discord/Issues#17]
結月のホームページの[認証済みサーバーページ](https://yudzuki.lunaproject.jp/verified/servers)にて、homeアイコンがしっかり表示されない問題
![image](https://user-images.githubusercontent.com/35885585/111444414-b1ca7880-874d-11eb-960f-e87f5343c704.png)

**Comment by Aoichaan0513** [comment]
修正済み
