### ISSUE TITLE
サーバー設定で選択肢にないリアクションが出てくる問題

### ISSUE THREAD

**Issue by narikakun** [LunaProject-Discord/Issues#18]
#.guildsettingsを利用した際に、選択肢にないリアクションが出てくる問題

**出し方**
1. #.guildsettingsを実行
2. AかBかCのリアクションを押す
3. リアクションで戻る
4. 出てくる

![image](https://user-images.githubusercontent.com/35885585/111646857-5c719280-8845-11eb-9a86-557f9315786d.png)

**Comment by Aoichaan0513** [comment]
ページから戻った時のリアクションとコマンド実行時のやつで違うの忘れてましたごめんなさい
近日中に直します。

**Comment by Aoichaan0513** [comment]
修正済み
