### ISSUE TITLE
ドメイン変更に関するまとめ

### ISSUE THREAD

**Issue by narikakun** [LunaProject-Discord/Issues#22]
まだドメイン変更に対応できていないページ等が複数あるのでまとめておきます。

【Twitter】
結月 -ゆづき- : https://twitter.com/Yudzuki_Discord
![image](https://user-images.githubusercontent.com/35885585/112087267-fb451880-8bd0-11eb-8dcd-110815b99147.png)

彩月 -さつき- : https://twitter.com/Satsuki_Discord
![image](https://user-images.githubusercontent.com/35885585/112087300-0dbf5200-8bd1-11eb-88d7-67c7fb8dfb19.png)

【Discord Bots】
招待URL ： https://top.gg/bot/553841194699063319/invite/
![image](https://user-images.githubusercontent.com/35885585/112087545-7f979b80-8bd1-11eb-92ea-9f1bdbbc263a.png)

説明文 ： 画像の「こちら」のリンクが https://yudzuki.aoichaan0513.jp/ になっている。
![image](https://user-images.githubusercontent.com/35885585/112087583-93430200-8bd1-11eb-81f4-bda8d69c1648.png)

【ホームページ】
結月ホームページOGP ： https://yudzuki.lunaproject.jp/
![image](https://user-images.githubusercontent.com/35885585/112087777-f16fe500-8bd1-11eb-8d71-830d7b8d1420.png)

APIリファレンス ： https://yudzuki.lunaproject.jp/dashboard/page/reference
![image](https://user-images.githubusercontent.com/35885585/112087945-43b10600-8bd2-11eb-91e2-c998e8e60a07.png)

**Comment by Aoichaan0513** [comment]
Twitterとホームページのヘッダーを修正しました。

**Comment by Aoichaan0513** [comment]
Discord Botsのリンクを修正しました。

**Comment by Aoichaan0513** [comment]
他に無いようであれば閉じますね
