### ISSUE TITLE
help Embedにあるサポートサーバーへのリンクが切れている

### ISSUE THREAD

**Issue by m1sk9** [LunaProject-Discord/Issues#33]
## バグの説明
`#.help` で表示されるhelp EmbedにあるDiscord サーバー招待リンクがリンク切れを起こしている。

## 再現方法
- DMにて `#.help` を開く

## 想定された状況
サポートサーバーに参加できる。

## スクリーンショット
![Screenshot_20210721-083753.png](https://user-images.githubusercontent.com/82575685/126408611-7ec5d1c9-70f9-4ee0-9799-c553162ddcd0.png)

## 環境 
**スマホ**
 - デバイス: [例: Android]
 - OS: Android 11
 - Discordのバージョン 8.20

**Comment by Aoichaan0513** [comment]
大規模アップデートと同時に修正します。

**Comment by Aoichaan0513** [comment]
コード上での修正は完了、正式提供時にデプロイ。
