### ISSUE TITLE
#.about adminsの実行に時間が掛かる

### ISSUE THREAD

**Issue by narikakun** [LunaProject-Discord/Issues#39]
## バグの説明
#.about adminsを実行する際に40秒以上応答に時間がかかる。

## 再現手順
#.about adminsを実行する。

## スクリーンショット
こちらのサーバーに実際の動作があります。（スクリーンショットだと収まりきらない）
https://discord.gg/2wsmRD2mJc
https://discord.com/channels/639405784471568394/639757579920080937/877547380294176779
![image](https://user-images.githubusercontent.com/35885585/129908823-3b44f102-e1c8-40ab-b497-91d6348089f7.png)
![image](https://user-images.githubusercontent.com/35885585/129908838-6d57acc0-eac0-470b-ae87-160d3bec4cac.png)
![image](https://user-images.githubusercontent.com/35885585/129908861-fa45b6f9-3197-4884-9bc3-231ad3520116.png)

## 環境 
**デスクトップ**
 - OS: Windows
 - Discord: 通常版

**Comment by narikakun** [comment]
追記：応答までに約3分かかります。

**Comment by Aoichaan0513** [comment]
解決済み
