### ISSUE TITLE
フォローコマンドで解除が出来ない

### ISSUE THREAD

**Issue by narikakun** [LunaProject-Discord/Issues#40]
## バグの説明
フォローコマンド（#.follow）の解除（#.follow remove）を実行してもフォローが解除できない。
解除できない→フォローされる

## 再現手順
1. #.followを実行してフォローする
2. 結月によってフォローされる。
3. #,follow removeを実行してフォローを解除しようとする
4. 結月によってフォローされる

## 想定された状況
#.follow removeを実行するとフォローが解除される。

## スクリーンショット
![image](https://user-images.githubusercontent.com/35885585/131065471-510dc262-f270-419d-8903-74b3a9587c86.png)

## 環境 
**デスクトップ**
 - OS: Windows
 - Discord: 通常版
 - Discordのバージョン: 95006

**Comment by narikakun** [comment]
ゆうにゃん様によって発見されました。

**Comment by midorichaan** [comment]
ご報告ありがとうございます。運営チームのMidorichanです。
該当コマンドのソースコードを確認したところ、removeコマンドはおそらくないかと思われます。

**Comment by narikakun** [comment]
> ご報告ありがとうございます。運営チームのMidorichanです。
> 該当コマンドのソースコードを確認したところ、removeコマンドはおそらくないかと思われます。

なるほど、ではヘルプコマンドのほうが間違っているという事になりますかね。
#.help followにて確認すると、「#.follow remove」が使い方に記載されているのでこれで解除できると勘違いしてしまいます。。
![image](https://user-images.githubusercontent.com/35885585/131085257-6777d1ef-a5c5-4f35-b04a-843d611fec12.png)

訂正をよろしくお願いします。

**Comment by Aoichaan0513** [comment]
次期バージョンでは使い方から `{bot:prefix}follow remove` の文言を削除することで対処。
